services:
  - type: web
    name: blog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
